version: '3.8'

services:
  # STUN/TURN server for NAT traversal
  coturn:
    image: coturn/coturn:latest
    container_name: quasar-coturn
    network_mode: host
    volumes:
      - ./config/turnserver.conf:/etc/turnserver.conf
    restart: unless-stopped
    
  # Signaling server for connection coordination
  signaling:
    build:
      context: ./Server
      dockerfile: Dockerfile.signaling
    container_name: quasar-signaling
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=quasar
      - DB_USER=quasar
      - DB_PASSWORD=quasar_password
    depends_on:
      - database
    restart: unless-stopped
    
  # Database for storing device registration and authentication
  database:
    image: postgres:13-alpine
    container_name: quasar-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quasar
      - POSTGRES_PASSWORD=quasar_password
      - POSTGRES_DB=quasar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  # Reverse proxy for handling HTTPS and routing
  nginx:
    image: nginx:alpine
    container_name: quasar-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
      - ./static:/usr/share/nginx/html
    depends_on:
      - signaling
    restart: unless-stopped

volumes:
  postgres_data:
