#!/bin/bash

# Get the directory where the script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RESOURCES_DIR="$DIR/Resources"

# Launch the application using Mono
exec mono "$RESOURCES_DIR/Quasar.Server.exe" "$@"
